/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('commute_tracking').del();
  await knex('commute_tracking').insert([
    {
      id: 1,
      user_id: 1,
      commute_date: "2023-12-31",
      start_location: "High Park",
      end_location: "CN Tower",
      distance: 20.0,
      co2_saved_kg: 0.123,
      eco_score: 123,
    },
    {
      id: 2,
      user_id: 1,
      commute_date: "2024-01-01",
      start_location: "CN Tower",
      end_location: "Niagra Falls",
      distance: 250.0,
      co2_saved_kg: 13.0,
      eco_score: 123,
    },
    {
      id: 3,
      user_id: 1,
      commute_date: "2024-01-03",
      start_location: "TNV School",
      end_location: "Bell Street",
      distance: 15.0,
      co2_saved_kg: 1.0,
      eco_score: 123,
    },
    {
      id: 4,
      user_id: 1,
      commute_date: "2024-01-04",
      start_location: "Aga Khan Museum",
      end_location: "Ontario Science Center",
      distance: 20.0,
      co2_saved_kg: 3.0,
      eco_score: 323,
    },
    {
      id: 5,
      user_id: 1,
      commute_date: "2024-01-05",
      start_location: "High Park",
      end_location: "CN Tower",
      distance: 20.0,
      co2_saved_kg: 0.5,
      eco_score: 123,
    },
    {
      id: 6,
      user_id: 1,
      commute_date: "2024-01-06",
      start_location: "Harbour Front",
      end_location: "Downtown",
      distance: 15.0,
      co2_saved_kg: 3.0,
      eco_score: 123,
    },
    {
      id: 7,
      user_id: 1,
      commute_date: "2024-01-07",
      start_location: "High Park",
      end_location: "CN Tower",
      distance: 20.0,
      co2_saved_kg: 0.123,
      eco_score: 123,
    },
    {
      id: 8,
      user_id: 2,
      commute_date: "2023-12-31",
      start_location: "High Park",
      end_location: "CN Tower",
      distance: 20.0,
      co2_saved_kg: 0.123,
      eco_score: 123,
    },
    {
      id: 9,
      user_id: 2,
      commute_date: "2024-01-01",
      start_location: "CN Tower",
      end_location: "Niagra Falls",
      distance: 250.0,
      co2_saved_kg: 13.0,
      eco_score: 123,
    },
    {
      id: 10,
      user_id: 2,
      commute_date: "2024-01-03",
      start_location: "TNV School",
      end_location: "Bell Street",
      distance: 15.0,
      co2_saved_kg: 1.0,
      eco_score: 123,
    },
    {
      id: 11,
      user_id: 2,
      commute_date: "2024-01-04",
      start_location: "Aga Khan Museum",
      end_location: "Ontario Science Center",
      distance: 20.0,
      co2_saved_kg: 3.0,
      eco_score: 323,
    },
    {
      id: 12,
      user_id: 2,
      commute_date: "2024-01-05",
      start_location: "High Park",
      end_location: "CN Tower",
      distance: 20.0,
      co2_saved_kg: 0.5,
      eco_score: 123,
    },
    {
      id: 13,
      user_id: 2,
      commute_date: "2024-01-06",
      start_location: "Harbour Front",
      end_location: "Downtown",
      distance: 15.0,
      co2_saved_kg: 3.0,
      eco_score: 123,
    },
    {
      id: 14,
      user_id: 2,
      commute_date: "2024-01-07",
      start_location: "High Park",
      end_location: "CN Tower",
      distance: 20.0,
      co2_saved_kg: 0.123,
      eco_score: 123,
    },
    {
      id: 15,
      user_id: 3,
      commute_date: "2023-12-31",
      start_location: "High Park",
      end_location: "CN Tower",
      distance: 20.0,
      co2_saved_kg: 0.123,
      eco_score: 123,
    },
    {
      id: 16,
      user_id: 3,
      commute_date: "2024-01-01",
      start_location: "CN Tower",
      end_location: "Niagra Falls",
      distance: 250.0,
      co2_saved_kg: 13.0,
      eco_score: 123,
    },
    {
      id: 17,
      user_id: 3,
      commute_date: "2024-01-03",
      start_location: "TNV School",
      end_location: "Bell Street",
      distance: 15.0,
      co2_saved_kg: 1.0,
      eco_score: 123,
    },
    {
      id: 18,
      user_id: 3,
      commute_date: "2024-01-04",
      start_location: "Aga Khan Museum",
      end_location: "Ontario Science Center",
      distance: 20.0,
      co2_saved_kg: 3.0,
      eco_score: 323,
    },
    {
      id: 19,
      user_id: 3,
      commute_date: "2024-01-05",
      start_location: "High Park",
      end_location: "CN Tower",
      distance: 20.0,
      co2_saved_kg: 0.5,
      eco_score: 123,
    },
    {
      id: 20,
      user_id: 3,
      commute_date: "2024-01-06",
      start_location: "Harbour Front",
      end_location: "Downtown",
      distance: 15.0,
      co2_saved_kg: 3.0,
      eco_score: 123,
    },
    {
      id: 21,
      user_id: 3,
      commute_date: "2024-01-07",
      start_location: "High Park",
      end_location: "CN Tower",
      distance: 20.0,
      co2_saved_kg: 0.123,
      eco_score: 123,
    },
    {
      id: 22,
      user_id: 4,
      commute_date: "2023-12-31",
      start_location: "High Park",
      end_location: "CN Tower",
      distance: 20.0,
      co2_saved_kg: 0.123,
      eco_score: 123,
    },
    {
      id: 23,
      user_id: 4,
      commute_date: "2024-01-01",
      start_location: "CN Tower",
      end_location: "Niagra Falls",
      distance: 250.0,
      co2_saved_kg: 13.0,
      eco_score: 123,
    },
    {
      id: 24,
      user_id: 4,
      commute_date: "2024-01-03",
      start_location: "TNV School",
      end_location: "Bell Street",
      distance: 15.0,
      co2_saved_kg: 1.0,
      eco_score: 123,
    },
    {
      id: 25,
      user_id: 4,
      commute_date: "2024-01-04",
      start_location: "Aga Khan Museum",
      end_location: "Ontario Science Center",
      distance: 20.0,
      co2_saved_kg: 3.0,
      eco_score: 323,
    },
    {
      id: 26,
      user_id: 4,
      commute_date: "2024-01-05",
      start_location: "High Park",
      end_location: "CN Tower",
      distance: 20.0,
      co2_saved_kg: 0.5,
      eco_score: 123,
    },
    {
      id: 27,
      user_id: 4,
      commute_date: "2024-01-06",
      start_location: "Harbour Front",
      end_location: "Downtown",
      distance: 15.0,
      co2_saved_kg: 3.0,
      eco_score: 123,
    },
    {
      id: 28,
      user_id: 4,
      commute_date: "2024-01-07",
      start_location: "High Park",
      end_location: "CN Tower",
      distance: 20.0,
      co2_saved_kg: 0.123,
      eco_score: 123,
    },
    {
      id: 29,
      user_id: 5,
      commute_date: "2023-12-31",
      start_location: "High Park",
      end_location: "CN Tower",
      distance: 20.0,
      co2_saved_kg: 0.123,
      eco_score: 123,
    },
    {
      id: 30,
      user_id: 5,
      commute_date: "2024-01-01",
      start_location: "CN Tower",
      end_location: "Niagra Falls",
      distance: 250.0,
      co2_saved_kg: 13.0,
      eco_score: 123,
    },
    {
      id: 31,
      user_id: 5,
      commute_date: "2024-01-03",
      start_location: "TNV School",
      end_location: "Bell Street",
      distance: 15.0,
      co2_saved_kg: 1.0,
      eco_score: 123,
    },
    {
      id: 32,
      user_id: 5,
      commute_date: "2024-01-04",
      start_location: "Aga Khan Museum",
      end_location: "Ontario Science Center",
      distance: 20.0,
      co2_saved_kg: 3.0,
      eco_score: 323,
    },
    {
      id: 33,
      user_id: 5,
      commute_date: "2024-01-05",
      start_location: "High Park",
      end_location: "CN Tower",
      distance: 20.0,
      co2_saved_kg: 0.5,
      eco_score: 123,
    },
    {
      id: 34,
      user_id: 5,
      commute_date: "2024-01-06",
      start_location: "Harbour Front",
      end_location: "Downtown",
      distance: 15.0,
      co2_saved_kg: 3.0,
      eco_score: 123,
    },
    {
      id: 35,
      user_id: 5,
      commute_date: "2024-01-07",
      start_location: "High Park",
      end_location: "CN Tower",
      distance: 20.0,
      co2_saved_kg: 0.123,
      eco_score: 123,
    },
  ]);
};